#!/usr/bin/env python3
"""turn-end.py — emit harness-generated ground truth at the end of every turn.

Claude Code Stop hook. The companion to session-start.py: that one anchors the
*first* turn, this one anchors *every* turn.

WHY THIS EXISTS
    An agent's claims about what it did are unverifiable from the transcript alone
    — a fabricated "I committed that" reads exactly like a real one. This hook
    prints the facts an agent is most likely to get wrong, generated by the harness
    rather than by the model, immediately after the model stops talking.

    The check is then mechanical and requires no expertise: read the model's claim,
    read the line below it. If the model said it committed and the SHA did not
    move, the claim is false. No judgement call, no re-reading the code.

    It reports DELTAS, not just state. A number sitting there is easy to ignore;
    "BUILT 33->34" is not.

WHAT IT REPORTS
    commit        HEAD short SHA. Catches invented commits.
    tree          clean, or number of modified files. Catches "I made the change"
                  when nothing moved, and "only that file changed" when 12 did.
    ledger        BUILT/PARTIAL/MISSING counts from LEDGER.md. Catches invented
                  status flips.
    verify-later  pending deferred-check count. Catches "I logged a check".
    build         whether any build source is newer than its .min twin. Catches
                  "I rebuilt" when npm run build never ran — the highest-frequency
                  silent failure in this repo, since editing source without
                  rebuilding has no visible effect on the served site.

    The source->output pairs are parsed out of package.json's minify scripts, which
    CLAUDE.md names as their single source. Nothing is hardcoded here.

OUTPUT CONTRACT
    Prints one JSON object on stdout:
      {"systemMessage": "<one or two lines shown to the user>",
       "suppressOutput": true}
    Exit 0 always, and never sets `continue: false`. A canary that can block a
    turn is a liability, not a safeguard.

STATE
    Previous snapshot is kept OUTSIDE the repo, at
    ~/.claude/turn-state/<hash-of-project-dir>.json — this repo is the deployed
    site, and a state file inside it would both publish and dirty the working
    tree it is trying to measure.

    Every turn is also APPENDED to <hash>.log next to it. The transcript line
    scrolls away; the log does not. Open it as a file to review a whole session's
    real state changes in order, or read it back to prove the hook fired at all.

TEST IT
    echo '{}' | python3 .claude/hooks/turn-end.py | python3 -m json.tool
"""
import hashlib
import importlib.util
import json
import os
import re
import shlex
import subprocess
import sys

ROOT = os.environ.get("CLAUDE_PROJECT_DIR") or os.getcwd()
STATE_DIR = os.path.join(os.path.expanduser("~"), ".claude", "turn-state")


def sh(*args):
    try:
        out = subprocess.run(args, cwd=ROOT, capture_output=True, text=True, timeout=5)
        return out.stdout.strip() if out.returncode == 0 else None
    except Exception:
        return None


def read(name):
    try:
        with open(os.path.join(ROOT, name), "r", encoding="utf-8") as fh:
            return fh.read()
    except OSError:
        return None


def load_session_start():
    """Reuse session-start.py's parsers instead of duplicating them.

    Its main() is guarded by __name__, so importing has no side effects.
    """
    path = os.path.join(ROOT, ".claude", "hooks", "session-start.py")
    prior = sys.dont_write_bytecode
    sys.dont_write_bytecode = True  # a __pycache__/ here would dirty the tree we measure
    try:
        spec = importlib.util.spec_from_file_location("_session_start", path)
        mod = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(mod)
        return mod
    except Exception:
        return None
    finally:
        sys.dont_write_bytecode = prior


def build_pairs():
    """Derive (input, output) pairs from package.json's minify scripts.

    cleancss -o OUT IN...   |   terser IN -o OUT -c -m
    """
    raw = read("package.json")
    if not raw:
        return []
    try:
        scripts = json.loads(raw).get("scripts", {})
    except ValueError:
        return []

    pairs = []
    for name, script in scripts.items():
        if not name.startswith("minify:"):
            continue
        for cmd in script.split("&&"):
            try:
                toks = shlex.split(cmd.strip())
            except ValueError:
                continue
            if not toks:
                continue
            out, ins, i = None, [], 1
            while i < len(toks):
                t = toks[i]
                if t == "-o" and i + 1 < len(toks):
                    out = toks[i + 1]
                    i += 2
                    continue
                if not t.startswith("-"):
                    ins.append(t)
                i += 1
            if out:
                pairs.extend((src, out) for src in ins)
    return pairs


def build_state():
    """'ok', 'STALE', or None when it cannot be determined."""
    pairs = build_pairs()
    if not pairs:
        return None
    stale = False
    seen = False
    for src, out in pairs:
        sp, op = os.path.join(ROOT, src), os.path.join(ROOT, out)
        try:
            s, o = os.path.getmtime(sp), os.path.getmtime(op)
        except OSError:
            continue  # gitignored source or output not built yet — not our alarm
        seen = True
        if s > o:
            stale = True
    if not seen:
        return None
    return "STALE" if stale else "ok"


def snapshot():
    snap = {}

    sha = sh("git", "rev-parse", "--short", "HEAD")
    if sha:
        snap["commit"] = sha

    porcelain = sh("git", "status", "--porcelain")
    if porcelain is not None:
        n = len([l for l in porcelain.splitlines() if l.strip()])
        snap["tree"] = n

    ss = load_session_start()
    if ss:
        ledger = read("LEDGER.md")
        if ledger:
            try:
                _, c = ss.ledger_summary(ledger)
                snap["built"] = c["BUILT"]
                snap["partial"] = c["PARTIAL"]
                snap["missing"] = c["MISSING"]
            except Exception:
                pass
        vl = read("VERIFY-LATER.md")
        if vl:
            try:
                snap["vl"] = ss.verify_later_summary(vl)[0]
            except Exception:
                pass

    b = build_state()
    if b:
        snap["build"] = b

    return snap


def _key():
    return hashlib.md5(ROOT.encode("utf-8")).hexdigest()[:12]


def state_path():
    return os.path.join(STATE_DIR, _key() + ".json")


def log_path():
    return os.path.join(STATE_DIR, _key() + ".log")


def append_log(msg):
    """Durable record. The transcript line scrolls away; this does not."""
    try:
        os.makedirs(STATE_DIR, exist_ok=True)
        stamp = subprocess.run(
            ["date", "-u", "+%Y-%m-%dT%H:%M:%SZ"], capture_output=True, text=True, timeout=5
        ).stdout.strip()
        with open(log_path(), "a", encoding="utf-8") as fh:
            fh.write("%s  %s\n" % (stamp, msg.replace("\n", "\n" + " " * 22)))
    except Exception:
        pass


def load_previous():
    try:
        with open(state_path(), "r", encoding="utf-8") as fh:
            return json.load(fh)
    except Exception:
        return None


def save(snap):
    try:
        os.makedirs(STATE_DIR, exist_ok=True)
        with open(state_path(), "w", encoding="utf-8") as fh:
            json.dump(snap, fh)
    except OSError:
        pass


def tree_str(n):
    return "clean" if n == 0 else "%d file%s" % (n, "" if n == 1 else "s")


def render(snap):
    bits = []
    if "commit" in snap:
        bits.append(snap["commit"])
    if "tree" in snap:
        bits.append("tree " + tree_str(snap["tree"]))
    if "built" in snap:
        bits.append("ledger %dB/%dP/%dM" % (snap["built"], snap["partial"], snap["missing"]))
    if "vl" in snap:
        bits.append("verify-later %d" % snap["vl"])
    if "build" in snap:
        bits.append("build " + snap["build"])
    return "state | " + " | ".join(bits)


def render_delta(prev, snap):
    if not prev:
        return None
    d = []
    if prev.get("commit") != snap.get("commit") and "commit" in snap:
        d.append("commit %s->%s" % (prev.get("commit", "?"), snap["commit"]))
    if prev.get("tree") != snap.get("tree") and "tree" in snap:
        d.append("tree %s->%s" % (tree_str(prev.get("tree", 0)), tree_str(snap["tree"])))
    for key, label in (("built", "BUILT"), ("partial", "PARTIAL"), ("missing", "MISSING")):
        if key in snap and prev.get(key) != snap.get(key):
            d.append("%s %s->%s" % (label, prev.get(key, "?"), snap[key]))
    if "vl" in snap and prev.get("vl") != snap.get("vl"):
        d.append("verify-later %s->%s" % (prev.get("vl", "?"), snap["vl"]))
    if "build" in snap and prev.get("build") != snap.get("build"):
        d.append("build %s->%s" % (prev.get("build", "?"), snap["build"]))
    return "  changed: " + ", ".join(d) if d else None


def main():
    snap = snapshot()
    if not snap:
        sys.exit(0)  # no project system here; stay silent

    prev = load_previous()
    save(snap)

    msg = render(snap)
    delta = render_delta(prev, snap)
    if delta:
        msg += "\n" + delta

    append_log(msg)
    print(json.dumps({"systemMessage": msg, "suppressOutput": True}))
    sys.exit(0)


if __name__ == "__main__":
    try:
        main()
    except Exception:
        sys.exit(0)  # never block a turn
