#!/usr/bin/env python3
"""turn-end.py — emit harness-generated ground truth at the end of every turn.

Claude Code Stop hook. The companion to session-start.py: that one anchors the
*first* turn, this one anchors *every* turn.

WHY THIS EXISTS
    An agent's claims about what it did are unverifiable from the transcript alone
    — a fabricated "I committed that" reads exactly like a real one. This hook
    prints the facts an agent is most likely to get wrong, generated by the harness
    rather than by the model, immediately after the model stops talking.

    The check is then mechanical and requires no expertise: read the model's claim,
    read the line below it. If the model said it committed and the SHA did not
    move, the claim is false. No judgement call, no re-reading the code.

    It reports DELTAS, not just state. A number sitting there is easy to ignore;
    "BUILT 33->34" is not.

    Commits are reported SEPARATELY from the rest of the deltas, on their own
    `commits:` line that names every commit in the turn. A turn is exactly one
    canary line but can be any number of commits, so folding them into a single
    `commit a->b` pair silently drops everything in between.

WHAT IT REPORTS
    session       Session ordinal, Claude Code's own title when it has one, and
                  the short id — e.g. `S-07 Canary check (b9eaefa8)`, or
                  `S-08 (6bc5dbd7)` for a session that never got a title. Not a
                  correctness check; it is a navigation key. The log interleaves
                  every session that ever ran in this repo, so without it you
                  cannot tell which run a line belongs to.

                  The ORDINAL is the part that always exists, and that is the
                  whole reason it exists. Claude Code writes an `ai-title` record
                  exactly ONCE, from the opening prompt, and never revisits the
                  decision — a one-word opener ("test", "hi") is declined
                  outright and no `ai-title` record is ever written for that
                  session. Measured across this project's transcripts: every
                  session carries at most one distinct `ai-title` value,
                  re-persisted once per turn, so the repeated records are copies
                  and not revisions. The hook therefore assigns its own S-NN on
                  a session's first turn and reuses it on every turn after.

                  NOT the same as "the session has no name anywhere". The VS Code
                  session list still shows a label for an untitled session, and
                  it appears to derive one at display time from the first prompt
                  with real content — skipping an opening "test". That label is
                  not stored as a title field anywhere; the only trace of it in
                  the transcript is the `last-prompt` records it is read from.
                  This hook does not currently use that fallback, so the canary
                  line and the VS Code session list can disagree on an untitled
                  session. Reading the first substantial `last-prompt` here would
                  close that gap if the divergence ever becomes annoying.

                  Numbering starts at S-01 and counts sessions the hook observes
                  from that point on. Sessions that ran before the counter
                  existed are deliberately unnumbered — backfilling them would
                  invent an ordering the log cannot support.

                  The title is read from the transcript's last `ai-title` record
                  and from nowhere else. There is deliberately no way to attach a
                  name by hand: an override was tried and removed, because a
                  hand-set string renders identically to a real title and so
                  makes the canary line assert a name that exists nowhere outside
                  this hook — the exact failure mode the whole file exists to
                  prevent. When the title is absent, the field shows the ordinal
                  and the id, which are both true. The short id is also the
                  transcript's filename under ~/.claude/projects/<slug>/.
    commit        HEAD short SHA. Catches invented commits.
    tree          clean, or number of modified files. Catches "I made the change"
                  when nothing moved, and "only that file changed" when 12 did.
    ledger        BUILT/PARTIAL/MISSING counts from LEDGER.md. Catches invented
                  status flips.
    verify-later  pending deferred-check count. Catches "I logged a check".
    build         whether any build source is newer than its .min twin. Catches
                  "I rebuilt" when npm run build never ran — the highest-frequency
                  silent failure in this repo, since editing source without
                  rebuilding has no visible effect on the served site.
    reply         Turn number within this session, counted per session id so it
                  restarts at #1 on every new run. Catches a skipped turn (the
                  hook did not fire) and shows how deep a session has gone.

    The source->output pairs are parsed out of package.json's minify scripts, which
    CLAUDE.md names as their single source. Nothing is hardcoded here.

OUTPUT CONTRACT
    Prints one JSON object on stdout:
      {"systemMessage": "<one or two lines shown to the user>",
       "suppressOutput": true}
    Exit 0 always, and never sets `continue: false`. A canary that can block a
    turn is a liability, not a safeguard.

STATE
    Previous snapshot is kept OUTSIDE the repo, at
    ~/.claude/turn-state/<hash-of-project-dir>.json — this repo is the deployed
    site, and a state file inside it would both publish and dirty the working
    tree it is trying to measure.

    Per-session turn counters live beside it in <hash>.replies.json, trimmed to
    the 50 most recent sessions.

    Session ordinals live in <hash>.sessions.json as {"next": N, "ids": {...}},
    trimmed to the 200 most recent sessions. `next` is stored rather than derived
    from the map so the counter stays monotonic across a trim — a reused S-number
    would defeat the point of having one.

    Every turn is also APPENDED to <hash>.log next to it. The transcript line
    scrolls away; the log does not. Open it as a file to review a whole session's
    real state changes in order, or read it back to prove the hook fired at all.
    README.md in that directory explains every field and what should alarm you.

TEST IT
    echo '{}' | python3 .claude/hooks/turn-end.py | python3 -m json.tool
"""
import datetime
import hashlib
import importlib.util
import json
import os
import re
import shlex
import subprocess
import sys

ROOT = os.environ.get("CLAUDE_PROJECT_DIR") or os.getcwd()
STATE_DIR = os.path.join(os.path.expanduser("~"), ".claude", "turn-state")
GMT4 = datetime.timezone(datetime.timedelta(hours=4))


def sh(*args):
    try:
        out = subprocess.run(args, cwd=ROOT, capture_output=True, text=True, timeout=5)
        return out.stdout.strip() if out.returncode == 0 else None
    except Exception:
        return None


def read(name):
    try:
        with open(os.path.join(ROOT, name), "r", encoding="utf-8") as fh:
            return fh.read()
    except OSError:
        return None


def load_session_start():
    """Reuse session-start.py's parsers instead of duplicating them.

    Its main() is guarded by __name__, so importing has no side effects.
    """
    path = os.path.join(ROOT, ".claude", "hooks", "session-start.py")
    prior = sys.dont_write_bytecode
    sys.dont_write_bytecode = True  # a __pycache__/ here would dirty the tree we measure
    try:
        spec = importlib.util.spec_from_file_location("_session_start", path)
        mod = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(mod)
        return mod
    except Exception:
        return None
    finally:
        sys.dont_write_bytecode = prior


def build_pairs():
    """Derive (input, output) pairs from package.json's minify scripts.

    cleancss -o OUT IN...   |   terser IN -o OUT -c -m
    """
    raw = read("package.json")
    if not raw:
        return []
    try:
        scripts = json.loads(raw).get("scripts", {})
    except ValueError:
        return []

    pairs = []
    for name, script in scripts.items():
        if not name.startswith("minify:"):
            continue
        for cmd in script.split("&&"):
            try:
                toks = shlex.split(cmd.strip())
            except ValueError:
                continue
            if not toks:
                continue
            out, ins, i = None, [], 1
            while i < len(toks):
                t = toks[i]
                if t == "-o" and i + 1 < len(toks):
                    out = toks[i + 1]
                    i += 2
                    continue
                if not t.startswith("-"):
                    ins.append(t)
                i += 1
            if out:
                pairs.extend((src, out) for src in ins)
    return pairs


def build_state():
    """'ok', 'STALE', or None when it cannot be determined."""
    pairs = build_pairs()
    if not pairs:
        return None
    stale = False
    seen = False
    for src, out in pairs:
        sp, op = os.path.join(ROOT, src), os.path.join(ROOT, out)
        try:
            s, o = os.path.getmtime(sp), os.path.getmtime(op)
        except OSError:
            continue  # gitignored source or output not built yet — not our alarm
        seen = True
        if s > o:
            stale = True
    if not seen:
        return None
    return "STALE" if stale else "ok"


def snapshot():
    snap = {}

    sha = sh("git", "rev-parse", "--short", "HEAD")
    if sha:
        snap["commit"] = sha

    porcelain = sh("git", "status", "--porcelain")
    if porcelain is not None:
        n = len([l for l in porcelain.splitlines() if l.strip()])
        snap["tree"] = n

    ss = load_session_start()
    if ss:
        ledger = read("LEDGER.md")
        if ledger:
            try:
                _, c = ss.ledger_summary(ledger)
                snap["built"] = c["BUILT"]
                snap["partial"] = c["PARTIAL"]
                snap["missing"] = c["MISSING"]
            except Exception:
                pass
        vl = read("VERIFY-LATER.md")
        if vl:
            try:
                snap["vl"] = ss.verify_later_summary(vl)[0]
            except Exception:
                pass

    b = build_state()
    if b:
        snap["build"] = b

    return snap


def hook_input():
    """The Stop payload Claude Code writes to stdin. {} when run by hand."""
    try:
        if sys.stdin.isatty():
            return {}
        raw = sys.stdin.read()
        return json.loads(raw) if raw.strip() else {}
    except Exception:
        return {}


def transcript_path(payload):
    """Payload's path if given, else reconstruct it from the session id.

    Transcripts live at ~/.claude/projects/<slug>/<session-id>.jsonl, where the
    slug is the project path with every '/' and '.' turned into '-'.
    """
    p = payload.get("transcript_path")
    if p and os.path.exists(p):
        return p
    sid = payload.get("session_id")
    if not sid:
        return None
    slug = re.sub(r"[/.]", "-", ROOT)
    guess = os.path.join(os.path.expanduser("~"), ".claude", "projects", slug, sid + ".jsonl")
    return guess if os.path.exists(guess) else None


def session_label(payload):
    """'S-07 Canary check (b9eaefa8)', 'S-08 (6bc5dbd7)', or None.

    Three parts, each omitted when unavailable. The ordinal is the one that
    always resolves — see session_ordinal for why a title often does not.

    Claude Code emits its `ai-title` record once per turn but only ever with one
    value per session, so the last one is read purely because it is the cheapest
    to reach while streaming the file.
    """
    sid = payload.get("session_id") or ""
    short = sid[:8] or None
    ordinal = session_ordinal(sid)

    path = transcript_path(payload)
    title = None
    if path:
        try:
            with open(path, "r", encoding="utf-8", errors="replace") as fh:
                for line in fh:
                    if '"ai-title"' not in line:  # cheap filter; parsing every line is the cost
                        continue
                    try:
                        obj = json.loads(line)
                    except ValueError:
                        continue
                    if obj.get("type") == "ai-title" and obj.get("aiTitle"):
                        title = obj["aiTitle"].strip()
        except OSError:
            pass

    if title and len(title) > 40:
        title = title[:39].rstrip() + "…"

    parts = []
    if ordinal:
        parts.append("S-%02d" % ordinal)
    if title:
        parts.append(title)
    if short:
        # bare when it stands alone, parenthesised when it trails something
        parts.append("(%s)" % short if parts else short)
    return " ".join(parts) or None


def _key():
    return hashlib.md5(ROOT.encode("utf-8")).hexdigest()[:12]


def state_path():
    return os.path.join(STATE_DIR, _key() + ".json")


def log_path():
    return os.path.join(STATE_DIR, _key() + ".log")


def append_log(msg):
    """Durable record. The transcript line scrolls away; this does not.

    Stamps are GMT+4 (Azat's wall clock), written with an explicit `(GMT+04)`
    marker so the log is unambiguous at a glance. The offset is fixed, not the
    machine's local zone — a run from another timezone still lands on the same
    timeline as every earlier entry.

    Entries written before 2026-07-27 use an ISO `+04:00` suffix instead; same
    instant, older spelling.

    Entries are separated by a BLANK LINE. An entry is not always one line — a
    turn that moved something carries indented `commits:` and `changed:` lines
    too, and the commit list is one line per commit — so without the separator a
    wall of state lines and delta lines reads as one undifferentiated block. The
    blank line is what makes "one turn" visible at a glance. Nothing parses this
    file, so the separator costs nothing.
    """
    try:
        os.makedirs(STATE_DIR, exist_ok=True)
        stamp = datetime.datetime.now(GMT4).strftime("%Y-%m-%dT%H:%M:%S(GMT+04)")
        with open(log_path(), "a", encoding="utf-8") as fh:
            fh.write("%s  %s\n\n" % (stamp, msg.replace("\n", "\n" + " " * 22)))
    except Exception:
        pass


def sessions_path():
    return os.path.join(STATE_DIR, _key() + ".sessions.json")


def session_ordinal(sid):
    """This session's S-number — 1 for the first session the counter ever sees.

    Assigned on a session's first turn and stable for every turn after it. It
    exists because Claude Code's `ai-title` record often does not: it is written
    once from the opening prompt and never reconsidered, so a session opened with
    a single word ("test", "hi") never gets one at all. (The VS Code session list
    still shows that session a label, derived at display time from its first
    substantial prompt — but nothing writes it down, so it is not something a
    hook can read as a title.) An ordinal is assigned from the session id alone
    and cannot be declined.

    Never reused. `next` is persisted alongside the id map precisely so that
    trimming the map cannot walk the counter backwards onto a number some older
    session in the log already answers to.
    """
    if not sid:
        return None
    try:
        os.makedirs(STATE_DIR, exist_ok=True)
        try:
            with open(sessions_path(), "r", encoding="utf-8") as fh:
                data = json.load(fh)
            ids = data.get("ids")
            nxt = data.get("next")
            if not isinstance(ids, dict):
                ids = {}
            if not isinstance(nxt, int) or nxt < 1:
                # recover a sane counter from whatever the map still holds
                nxt = max([v for v in ids.values() if isinstance(v, int)] or [0]) + 1
        except Exception:
            ids, nxt = {}, 1

        n = ids.pop(sid, None)
        if not isinstance(n, int):
            n, nxt = nxt, nxt + 1
        ids[sid] = n  # re-inserted last, so the trim drops the stalest ids first
        for stale in list(ids)[:-200]:
            del ids[stale]

        with open(sessions_path(), "w", encoding="utf-8") as fh:
            json.dump({"next": nxt, "ids": ids}, fh)
        return n
    except Exception:
        return None


def replies_path():
    return os.path.join(STATE_DIR, _key() + ".replies.json")


def bump_reply(sid):
    """Nth turn of THIS session. None when the session is unknown.

    Kept per-session, not per-project: the counter has to restart when a new
    session starts, or 'reply #' says nothing about where you are in a run.
    Re-inserting the live session at the end makes the dict least-recently-used
    ordered, so the trim drops the stalest sessions rather than the newest.
    """
    if not sid:
        return None
    try:
        os.makedirs(STATE_DIR, exist_ok=True)
        try:
            with open(replies_path(), "r", encoding="utf-8") as fh:
                counts = json.load(fh)
            if not isinstance(counts, dict):
                counts = {}
        except Exception:
            counts = {}

        n = int(counts.pop(sid, 0) or 0) + 1
        counts[sid] = n
        for stale in list(counts)[:-50]:  # bound the file; one entry per session
            del counts[stale]

        with open(replies_path(), "w", encoding="utf-8") as fh:
            json.dump(counts, fh)
        return n
    except Exception:
        return None


def load_previous():
    try:
        with open(state_path(), "r", encoding="utf-8") as fh:
            return json.load(fh)
    except Exception:
        return None


def save(snap):
    try:
        os.makedirs(STATE_DIR, exist_ok=True)
        with open(state_path(), "w", encoding="utf-8") as fh:
            json.dump(snap, fh)
    except OSError:
        pass


def tree_str(n):
    return "clean" if n == 0 else "%d file%s" % (n, "" if n == 1 else "s")


def render(snap, session=None, reply=None):
    bits = []
    if session:
        bits.append(session)  # deliberately not in snap: context, not project state,
                              # so render_delta never reports it as a change
    if "commit" in snap:
        bits.append(snap["commit"])
    if "tree" in snap:
        bits.append("tree " + tree_str(snap["tree"]))
    if "built" in snap:
        bits.append("ledger %dB/%dP/%dM" % (snap["built"], snap["partial"], snap["missing"]))
    if "vl" in snap:
        bits.append("verify-later %d" % snap["vl"])
    if "build" in snap:
        bits.append("build " + snap["build"])
    if reply:
        bits.append("reply #%d" % reply)
    return "state | " + " | ".join(bits)


COMMIT_CAP = 10  # a pull can drag in hundreds; the log is for reading, not archiving
COMMIT_WIDTH = 60


def render_commits(prev, snap):
    """The turn's commits, oldest first, one per line — or None.

    A turn is one canary line but can be any number of commits, so neither the
    SHA on the state line nor a `commit a->b` pair says what actually landed.
    This walks the real range instead.

    None when the range cannot be walked or comes back empty — an amend, reset,
    or rebase leaves the previous SHA unreachable from HEAD, and there is no
    honest list to print. The caller falls back to the `commit a->b` form, which
    is still true: the SHA moved, and that is the claim worth checking.
    """
    if not prev:
        return None
    prev_sha, sha = prev.get("commit"), snap.get("commit")
    if not prev_sha or not sha or prev_sha == sha:
        return None

    out = sh("git", "log", "--reverse", "--format=%h %s", "%s..%s" % (prev_sha, sha))
    rows = [l.strip() for l in (out or "").splitlines() if l.strip()]
    if not rows:
        return None

    dropped = len(rows) - COMMIT_CAP
    if dropped > 0:
        rows = rows[:COMMIT_CAP] + ["… +%d more" % dropped]
    rows = [r if len(r) <= COMMIT_WIDTH else r[: COMMIT_WIDTH - 1].rstrip() + "…" for r in rows]

    pad = "\n" + " " * len("  commits: ")  # continuations align under the first SHA
    return "  commits: " + pad.join(rows)


def render_delta(prev, snap, skip_commit=False):
    if not prev:
        return None
    d = []
    if not skip_commit and prev.get("commit") != snap.get("commit") and "commit" in snap:
        d.append("commit %s->%s" % (prev.get("commit", "?"), snap["commit"]))
    if prev.get("tree") != snap.get("tree") and "tree" in snap:
        d.append("tree %s->%s" % (tree_str(prev.get("tree", 0)), tree_str(snap["tree"])))
    for key, label in (("built", "BUILT"), ("partial", "PARTIAL"), ("missing", "MISSING")):
        if key in snap and prev.get(key) != snap.get(key):
            d.append("%s %s->%s" % (label, prev.get(key, "?"), snap[key]))
    if "vl" in snap and prev.get("vl") != snap.get("vl"):
        d.append("verify-later %s->%s" % (prev.get("vl", "?"), snap["vl"]))
    if "build" in snap and prev.get("build") != snap.get("build"):
        d.append("build %s->%s" % (prev.get("build", "?"), snap["build"]))
    return "  changed: " + ", ".join(d) if d else None


def main():
    payload = hook_input()
    snap = snapshot()
    if not snap:
        sys.exit(0)  # no project system here; stay silent

    prev = load_previous()
    save(snap)

    msg = render(snap, session_label(payload), bump_reply(payload.get("session_id")))
    commits = render_commits(prev, snap)
    delta = render_delta(prev, snap, skip_commit=commits is not None)
    for extra in (commits, delta):
        if extra:
            msg += "\n" + extra

    append_log(msg)
    print(json.dumps({"systemMessage": msg, "suppressOutput": True}))
    sys.exit(0)


if __name__ == "__main__":
    try:
        main()
    except Exception:
        sys.exit(0)  # never block a turn
